### ISSUE TITLE
Implement evaluation context transformer requirement (1.6.1) and test

### ISSUE THREAD

**Issue by skyerus** [open-feature/golang-sdk#16]
Requirement 1.6.1

> The client SHOULD transform the evaluation context using the provider's context transformer function if one is defined, before passing the result of the transformation to the provider's flag resolution functions.

Replace [this todo](https://github.com/open-feature/golang-sdk/blob/main/pkg/openfeature/client_test.go#L288) with the test.

**Comment by skyerus** [comment]
Without having access to generics implementing this requirement isn't as trivial as one would hope.

If I've understood the intent, we want to allow providers to transform the EvaluationContext into their own custom type.

The only way I can envision this happening is by changing the FeatureProvider's `EvaluationContext` function parameter to the `interface{}` type. This isn't ideal as it'd mean that the Provider would be forced to assert the `EvaluationContext`'s type in its calls. This would be especially cumbersome for Providers that don't want to transform an `EvaluationContext`, they'd still be forced to assert the `interface{}` to `EvaluationContext`.

Is this an acceptable downside? Can we find another way of achieving this behaviour without burdening the Providers with the type assertions?

@toddbaert @beeme1mr @james-milligan

**Comment by beeme1mr** [comment]
Technically this isn't required by the spec. Perhaps the go lang SDK simply doesn't support a context transformer.

There was recently a proposal to add support to the spec for [provider hooks](https://github.com/open-feature/spec/issues/113). Perhaps that would be sufficient in this case.

**Comment by skyerus** [comment]
> Technically this isn't required by the spec. Perhaps the go lang SDK simply doesn't support a context transformer.
> 
> There was recently a proposal to add support to the spec for [provider hooks](https://github.com/open-feature/spec/issues/113). Perhaps that would be sufficient in this case.

As this isn't strictly required by the spec I'm closing this. Perhaps it can be revisited when upgrading to 1.18
