### ISSUE TITLE
Rename getters to be more inline with Golang idioms

### ISSUE THREAD

**Issue by skyerus** [open-feature/golang-sdk#22]
Currently there are getters defined that are prefixed with `Get` e.g.
> GetBooleanValue(flag string, defaultValue bool, evalCtx EvaluationContext, options EvaluationOptions) (bool, error)

This goes against [Golang convention](https://go.dev/doc/effective_go#Getters). Renaming this example to just `BooleanValue` would be better practice.

**Comment by Akshit42-hue** [comment]
Hey @skyerus, can I work on it
