### ISSUE TITLE
Evaluation Context Handling 

### ISSUE THREAD

**Issue by james-milligan** [open-feature/golang-sdk#30]
In previous versions of the Golang-sdk `EvaluationContext` has been defined as an `interface{}`. In [this](https://github.com/open-feature/golang-sdk/commit/f0312d81766b1ac9849d4f3c31acf450b452e553) commit it has been updated to a `struct` containing required fields (currently just `TargetingKey` but likely to grow) with a nested `map[string]interface{}` under the `Attributes` field, to better comply to the spec.

I believe this may cause issues down the line for client applications needing to know if their properties are on the base struct or in the additional properties.
```
if evCtx.Yellow == true {
    return 'yellow'
}
```
turns into 
```
if evCtx.Attributes.Yellow == true {
    return 'yellow'
}
```

Following conversations with @skyerus we have identified 3 possible ways to resolve this, though this list likely isn't exhaustive:

1. Do nothing and handle the nesting within providers
2. Flatten the structure into a `map[string]interface{}` as standard and update the [provider interface](https://github.com/open-feature/golang-sdk/blob/91d68f3ffa9f698ffc313f2da3858e6ea33befb1/pkg/openfeature/provider.go#L15) method signatures to reflect this
3. Offer a `before hook` that will flatten the structure ([would require provider hooks](https://github.com/open-feature/research/pull/22)), similar outcome to doing nothing, but the hook would be directly linked to the sdk

Please let me know your thoughts

EDIT by @toddbaert :

Seems like we have a consensus, I will take this issue and action it.

**Comment by james-milligan** [comment]
@toddbaert @beeme1mr @skyerus @davejohnston

**Comment by skyerus** [comment]
If we flatten the structure into `map[string]interface{}` by inserting the rest of `EvaluationContext`'s fields (currently just `TargetingKey` into the map we run into the issue that providers would need to look up the key from the sdk (e.g. `targetingKey` vs `targeting-key`) which is undesirable.

**Comment by beeme1mr** [comment]
According to the spec, the targeting key is optional.

https://github.com/open-feature/spec/blob/main/specification/sections/03-evaluation-context.md#requirement-311

It's just a named property so we can properly map it to providers that required a unique identifier.

**Comment by beeme1mr** [comment]
I feel like option two would be bring us closer to other SDKs.

**Comment by toddbaert** [comment]
> I feel like option two would be bring us closer to other SDKs.

Agreed. I think this is also how `flagd` understand the evaluation context (as a flat object), which will bring those interfaces closer together. As mentioned before, I'd like flagd to eventually use the provider interface from the golang SDK, if reasonable.

**Comment by james-milligan** [comment]
That is correct, flagd expects a `map[string]interface{}`

I also agree that option 2 will be the cleanest approach for this

**Comment by beeme1mr** [comment]
@james-milligan are there any next steps here or can we close the issue?

**Comment by james-milligan** [comment]
as of yet the changes haven't been implemented, im happy to assign this to myself and implement the changes, provided that is ok with @toddbaert 
(if we still feel like this is a worthwhile change)

**Comment by toddbaert** [comment]
@james-milligan I think we should do this, yep! Go for it.

**Comment by james-milligan** [comment]
[I've opened up a draft PR for this. ](https://github.com/open-feature/golang-sdk/pull/51)I've opted to not introduce another type to wrap the `map[string]interface{}` to reduce confusion, but as the flattened context is returned by a function this would be very simple to implement.
