### ISSUE TITLE
[BUG] Typed ResolutionDetail structs have mulitple different `Value` values

### ISSUE THREAD

**Issue by agentgonzo** [open-feature/golang-sdk#57]
### Observed behavior

Looking at https://github.com/open-feature/golang-sdk/blob/main/pkg/openfeature/provider.go#L65-L68 and running the code, it is possible for a provider to return a struct for `BoolResolutionDetail` where there are two different `Value` elements, with different values.

eg
![image](https://user-images.githubusercontent.com/1652511/189887107-14c27a08-6561-4a41-9bc7-efe8c7638539.png)

It's been a while since I've done go coding, and this may be idiomatic, but to me it's confusing

### Expected Behavior

You should only be able to set one `Value` value

### Steps to reproduce

```go
	thing := openfeature.BoolResolutionDetail{
		Value: true,
		ResolutionDetail: openfeature.ResolutionDetail{
			Value: false,
		},
	}
```

**Comment by skyerus** [comment]
- [ ] https://github.com/open-feature/golang-sdk-contrib/issues/22
