### ISSUE TITLE
Write tests for each of the implemented spec requirements

### ISSUE THREAD

**Issue by skyerus** [open-feature/golang-sdk#7]
Spec requirements: https://github.com/open-feature/spec/blob/main/specification/flag-evaluation.md

An example of an implemented spec requirement that requires a test:

### Requirement 1.1.2
> The `API` MUST provide a function to set the global `provider` singleton, which accepts an API-conformant `provider` implementation.

**Comment by toddbaert** [comment]
Closed with https://github.com/open-feature/golang-sdk/pull/8
